add control key modal created
LibertyDSNP/provider-dashboard pull request #114
Opened 2024-01-26 00:08 UTC by claireolmstead

2024-02-05 23:41 UTC, rlaferla requested changes

2024-02-05 23:41 UTC, rlaferla commented on src/components/AddControlKey.svelte
> +    selected={$transactionSigningAddress}
`transactionSigningAddress` is obsolete.  Use `$user.signingKey` instead.  Also, do you need to bind the prop?

2024-02-05 23:41 UTC, rlaferla commented on src/components/AddControlKey.svelte
> +      let signingKeys = $transactionSigningAddress;
`transactionSigningAddress` is obsolete.

2024-02-05 23:41 UTC, rlaferla commented on src/components/AddControlKey.svelte
> +  import { dotApi, transactionSigningAddress, storeMsaInfo } from '$lib/stores';
`transactionSigningAddress` is obsolete.

2024-02-07 18:31 UTC, claireolmstead commented
closed in favor of #146

2024-02-07 18:31 UTC, closed without merging